name: CI-CD

on:
  push:
  release:
  pull_request:

jobs:
  test:
    name: Py${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      CI: 'true'
      OS: 'linux'
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout Pull Requests
        uses: actions/checkout@v6

      - name: Install Environment Dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y libgit2-dev xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest" 
          python-version: ${{ matrix.PYTHON_VERSION }}
          channel-priority: false    # "strict"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Setup environment
        run: |
          mamba install spyder
          pip install -e .
          conda list

  generate_artifacts:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Pull Requests
        uses: actions/checkout@v6

      - name: Install Environment Dependencies
        shell: bash
        run: |
          sudo apt-get update --fix-missing

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest" 
          python-version: 3.9
          channel-priority: false    # "strict"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Compute Version
        id: computed_version
        run: |
          if [[ ${{ github.event.release.tag_name != '' }} != false ]]
          then
            echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
          else
            echo ::set-output name=VERSION::$(echo "0.0.0")
          fi

      - name: Apply version
        run: |
          echo Version is ${{ steps.computed_version.outputs.VERSION }}
          # TODO apply version....
          
      - name: Setup environment
        run: |
          pip install sphinx sphinx-rtd-theme myst-parser sphinx-markdown-tables
          pip install --upgrade myst-parser
          # install spyder and semi-ate

      - name: Run Manifest Check
        run: |
          echo 'Check manifest of Pylab-ML'
          check-manifest

      - name: Build Sphinx
        run: |
            sphinx-build -b html docs/source/ docs/build/html

      - name: Upload docs to Github artifact
        uses: actions/upload-artifact@v6
        with:
          path: docs/build/html/*
          name: docs-output

      - name: Deploy preview
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/build/html
      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name != 'pull_request'
        with:
          folder: ./docs/build/html
          branch: docs
          target-folder: .
          clean-exclude: pr-preview

